/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: customer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "customer.pb-c.h"
void   credit_card__expiration__init
                     (CreditCard__Expiration         *message)
{
  static const CreditCard__Expiration init_value = CREDIT_CARD__EXPIRATION__INIT;
  *message = init_value;
}
void   credit_card__init
                     (CreditCard         *message)
{
  static const CreditCard init_value = CREDIT_CARD__INIT;
  *message = init_value;
}
size_t credit_card__get_packed_size
                     (const CreditCard *message)
{
  assert(message->base.descriptor == &credit_card__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t credit_card__pack
                     (const CreditCard *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &credit_card__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t credit_card__pack_to_buffer
                     (const CreditCard *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &credit_card__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreditCard *
       credit_card__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreditCard *)
     protobuf_c_message_unpack (&credit_card__descriptor,
                                allocator, len, data);
}
void   credit_card__free_unpacked
                     (CreditCard *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &credit_card__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   customer__init
                     (Customer         *message)
{
  static const Customer init_value = CUSTOMER__INIT;
  *message = init_value;
}
size_t customer__get_packed_size
                     (const Customer *message)
{
  assert(message->base.descriptor == &customer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t customer__pack
                     (const Customer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &customer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t customer__pack_to_buffer
                     (const Customer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &customer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Customer *
       customer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Customer *)
     protobuf_c_message_unpack (&customer__descriptor,
                                allocator, len, data);
}
void   customer__free_unpacked
                     (Customer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &customer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor credit_card__expiration__field_descriptors[2] =
{
  {
    "year",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CreditCard__Expiration, has_year),
    offsetof(CreditCard__Expiration, year),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "month",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CreditCard__Expiration, has_month),
    offsetof(CreditCard__Expiration, month),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned credit_card__expiration__field_indices_by_name[] = {
  1,   /* field[1] = month */
  0,   /* field[0] = year */
};
static const ProtobufCIntRange credit_card__expiration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor credit_card__expiration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreditCard.Expiration",
  "Expiration",
  "CreditCard__Expiration",
  "",
  sizeof(CreditCard__Expiration),
  2,
  credit_card__expiration__field_descriptors,
  credit_card__expiration__field_indices_by_name,
  1,  credit_card__expiration__number_ranges,
  (ProtobufCMessageInit) credit_card__expiration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue credit_card__status__enum_values_by_number[2] =
{
  { "VALID", "CREDIT_CARD__STATUS__VALID", 0 },
  { "CANCELLED", "CREDIT_CARD__STATUS__CANCELLED", 1 },
};
static const ProtobufCIntRange credit_card__status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex credit_card__status__enum_values_by_name[2] =
{
  { "CANCELLED", 1 },
  { "VALID", 0 },
};
const ProtobufCEnumDescriptor credit_card__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CreditCard.Status",
  "Status",
  "CreditCard__Status",
  "",
  2,
  credit_card__status__enum_values_by_number,
  2,
  credit_card__status__enum_values_by_name,
  1,
  credit_card__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor credit_card__field_descriptors[3] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CreditCard, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expiration",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CreditCard, expiration),
    &credit_card__expiration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CreditCard, has_status),
    offsetof(CreditCard, status),
    &credit_card__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned credit_card__field_indices_by_name[] = {
  1,   /* field[1] = expiration */
  0,   /* field[0] = number */
  2,   /* field[2] = status */
};
static const ProtobufCIntRange credit_card__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor credit_card__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreditCard",
  "CreditCard",
  "CreditCard",
  "",
  sizeof(CreditCard),
  3,
  credit_card__field_descriptors,
  credit_card__field_indices_by_name,
  1,  credit_card__number_ranges,
  (ProtobufCMessageInit) credit_card__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor customer__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Customer, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "age",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Customer, has_age),
    offsetof(Customer, age),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "credit_cards",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Customer, n_credit_cards),
    offsetof(Customer, credit_cards),
    &credit_card__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "premium",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Customer, has_premium),
    offsetof(Customer, premium),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned customer__field_indices_by_name[] = {
  1,   /* field[1] = age */
  2,   /* field[2] = credit_cards */
  0,   /* field[0] = name */
  3,   /* field[3] = premium */
};
static const ProtobufCIntRange customer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor customer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Customer",
  "Customer",
  "Customer",
  "",
  sizeof(Customer),
  4,
  customer__field_descriptors,
  customer__field_indices_by_name,
  1,  customer__number_ranges,
  (ProtobufCMessageInit) customer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
