/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: customer.proto */

#ifndef PROTOBUF_C_customer_2eproto__INCLUDED
#define PROTOBUF_C_customer_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "yara.pb-c.h"

typedef struct _CreditCard CreditCard;
typedef struct _CreditCard__Expiration CreditCard__Expiration;
typedef struct _Customer Customer;


/* --- enums --- */

typedef enum _CreditCard__Status {
  CREDIT_CARD__STATUS__VALID = 0,
  CREDIT_CARD__STATUS__CANCELLED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CREDIT_CARD__STATUS)
} CreditCard__Status;

/* --- messages --- */

struct  _CreditCard__Expiration
{
  ProtobufCMessage base;
  protobuf_c_boolean has_year;
  int32_t year;
  protobuf_c_boolean has_month;
  int32_t month;
};
#define CREDIT_CARD__EXPIRATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&credit_card__expiration__descriptor) \
    , 0, 0, 0, 0 }


struct  _CreditCard
{
  ProtobufCMessage base;
  char *number;
  CreditCard__Expiration *expiration;
  protobuf_c_boolean has_status;
  CreditCard__Status status;
};
#define CREDIT_CARD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&credit_card__descriptor) \
    , NULL, NULL, 0, CREDIT_CARD__STATUS__VALID }


struct  _Customer
{
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean has_age;
  int32_t age;
  size_t n_credit_cards;
  CreditCard **credit_cards;
  protobuf_c_boolean has_premium;
  protobuf_c_boolean premium;
};
#define CUSTOMER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&customer__descriptor) \
    , NULL, 0, 0, 0,NULL, 0, 0 }


/* CreditCard__Expiration methods */
void   credit_card__expiration__init
                     (CreditCard__Expiration         *message);
/* CreditCard methods */
void   credit_card__init
                     (CreditCard         *message);
size_t credit_card__get_packed_size
                     (const CreditCard   *message);
size_t credit_card__pack
                     (const CreditCard   *message,
                      uint8_t             *out);
size_t credit_card__pack_to_buffer
                     (const CreditCard   *message,
                      ProtobufCBuffer     *buffer);
CreditCard *
       credit_card__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   credit_card__free_unpacked
                     (CreditCard *message,
                      ProtobufCAllocator *allocator);
/* Customer methods */
void   customer__init
                     (Customer         *message);
size_t customer__get_packed_size
                     (const Customer   *message);
size_t customer__pack
                     (const Customer   *message,
                      uint8_t             *out);
size_t customer__pack_to_buffer
                     (const Customer   *message,
                      ProtobufCBuffer     *buffer);
Customer *
       customer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   customer__free_unpacked
                     (Customer *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CreditCard__Expiration_Closure)
                 (const CreditCard__Expiration *message,
                  void *closure_data);
typedef void (*CreditCard_Closure)
                 (const CreditCard *message,
                  void *closure_data);
typedef void (*Customer_Closure)
                 (const Customer *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor credit_card__descriptor;
extern const ProtobufCMessageDescriptor credit_card__expiration__descriptor;
extern const ProtobufCEnumDescriptor    credit_card__status__descriptor;
extern const ProtobufCMessageDescriptor customer__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_customer_2eproto__INCLUDED */
