// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/yara.proto

package yara

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModuleOptions struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RootMessage          string   `protobuf:"bytes,2,opt,name=root_message,json=rootMessage,proto3" json:"root_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleOptions) Reset()         { *m = ModuleOptions{} }
func (m *ModuleOptions) String() string { return proto.CompactTextString(m) }
func (*ModuleOptions) ProtoMessage()    {}
func (*ModuleOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_525dc6cd5d3d5c82, []int{0}
}

func (m *ModuleOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleOptions.Unmarshal(m, b)
}
func (m *ModuleOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleOptions.Marshal(b, m, deterministic)
}
func (m *ModuleOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleOptions.Merge(m, src)
}
func (m *ModuleOptions) XXX_Size() int {
	return xxx_messageInfo_ModuleOptions.Size(m)
}
func (m *ModuleOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleOptions proto.InternalMessageInfo

func (m *ModuleOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModuleOptions) GetRootMessage() string {
	if m != nil {
		return m.RootMessage
	}
	return ""
}

type FieldOptions struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ignore               bool     `protobuf:"varint,2,opt,name=ignore,proto3" json:"ignore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldOptions) Reset()         { *m = FieldOptions{} }
func (m *FieldOptions) String() string { return proto.CompactTextString(m) }
func (*FieldOptions) ProtoMessage()    {}
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_525dc6cd5d3d5c82, []int{1}
}

func (m *FieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions.Unmarshal(m, b)
}
func (m *FieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions.Marshal(b, m, deterministic)
}
func (m *FieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions.Merge(m, src)
}
func (m *FieldOptions) XXX_Size() int {
	return xxx_messageInfo_FieldOptions.Size(m)
}
func (m *FieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions proto.InternalMessageInfo

func (m *FieldOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldOptions) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

type MessageOptions struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageOptions) Reset()         { *m = MessageOptions{} }
func (m *MessageOptions) String() string { return proto.CompactTextString(m) }
func (*MessageOptions) ProtoMessage()    {}
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_525dc6cd5d3d5c82, []int{2}
}

func (m *MessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageOptions.Unmarshal(m, b)
}
func (m *MessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageOptions.Marshal(b, m, deterministic)
}
func (m *MessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageOptions.Merge(m, src)
}
func (m *MessageOptions) XXX_Size() int {
	return xxx_messageInfo_MessageOptions.Size(m)
}
func (m *MessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MessageOptions proto.InternalMessageInfo

func (m *MessageOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EnumOptions struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumOptions) Reset()         { *m = EnumOptions{} }
func (m *EnumOptions) String() string { return proto.CompactTextString(m) }
func (*EnumOptions) ProtoMessage()    {}
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_525dc6cd5d3d5c82, []int{3}
}

func (m *EnumOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumOptions.Unmarshal(m, b)
}
func (m *EnumOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumOptions.Marshal(b, m, deterministic)
}
func (m *EnumOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumOptions.Merge(m, src)
}
func (m *EnumOptions) XXX_Size() int {
	return xxx_messageInfo_EnumOptions.Size(m)
}
func (m *EnumOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumOptions.DiscardUnknown(m)
}

var xxx_messageInfo_EnumOptions proto.InternalMessageInfo

func (m *EnumOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

var E_ModuleOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*ModuleOptions)(nil),
	Field:         51503,
	Name:          "yara.module_options",
	Tag:           "bytes,51503,opt,name=module_options",
	Filename:      "pb/yara.proto",
}

var E_FieldOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldOptions)(nil),
	Field:         51504,
	Name:          "yara.field_options",
	Tag:           "bytes,51504,opt,name=field_options",
	Filename:      "pb/yara.proto",
}

var E_MessageOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*MessageOptions)(nil),
	Field:         51505,
	Name:          "yara.message_options",
	Tag:           "bytes,51505,opt,name=message_options",
	Filename:      "pb/yara.proto",
}

var E_EnumOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*EnumOptions)(nil),
	Field:         51506,
	Name:          "yara.enum_options",
	Tag:           "bytes,51506,opt,name=enum_options",
	Filename:      "pb/yara.proto",
}

func init() {
	proto.RegisterType((*ModuleOptions)(nil), "yara.ModuleOptions")
	proto.RegisterType((*FieldOptions)(nil), "yara.FieldOptions")
	proto.RegisterType((*MessageOptions)(nil), "yara.MessageOptions")
	proto.RegisterType((*EnumOptions)(nil), "yara.EnumOptions")
	proto.RegisterExtension(E_ModuleOptions)
	proto.RegisterExtension(E_FieldOptions)
	proto.RegisterExtension(E_MessageOptions)
	proto.RegisterExtension(E_EnumOptions)
}

func init() { proto.RegisterFile("pb/yara.proto", fileDescriptor_525dc6cd5d3d5c82) }

var fileDescriptor_525dc6cd5d3d5c82 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4d, 0x4b, 0xb5, 0x40,
	0x14, 0xc7, 0xb9, 0xcf, 0x73, 0xb9, 0xd4, 0xf1, 0x25, 0xb2, 0x88, 0x21, 0x8a, 0xbc, 0xd2, 0xe2,
	0xae, 0x14, 0x6a, 0xe7, 0x3e, 0x77, 0x97, 0x60, 0x68, 0x11, 0x6d, 0x6e, 0x9a, 0xa3, 0x08, 0x8e,
	0x47, 0x46, 0x5d, 0xf4, 0x35, 0xfa, 0x22, 0xbd, 0x7c, 0xc2, 0x70, 0x66, 0xf2, 0x2a, 0x85, 0xbb,
	0xf9, 0x9f, 0x97, 0x1f, 0x73, 0x7e, 0x60, 0xd5, 0x49, 0xf0, 0x1a, 0x8b, 0xd8, 0xaf, 0x05, 0xb6,
	0xe8, 0x2c, 0xfb, 0xf7, 0xb9, 0x9b, 0x23, 0xe6, 0x25, 0x0b, 0x64, 0x2d, 0xe9, 0xb2, 0x20, 0x65,
	0xcd, 0x8b, 0x28, 0xea, 0x16, 0x85, 0x9a, 0xf3, 0x22, 0xb0, 0xb6, 0x98, 0x76, 0x25, 0xbb, 0xaf,
	0xdb, 0x02, 0xab, 0xc6, 0x71, 0x60, 0x59, 0xc5, 0x9c, 0x91, 0x85, 0xbb, 0xd8, 0x1c, 0x52, 0xf9,
	0x76, 0xd6, 0x60, 0x0a, 0xc4, 0x76, 0xc7, 0x59, 0xd3, 0xc4, 0x39, 0x23, 0xff, 0x64, 0xcf, 0xe8,
	0x6b, 0x5b, 0x55, 0xf2, 0x42, 0x30, 0xa3, 0x82, 0x95, 0xe9, 0x1c, 0xe6, 0x0c, 0x56, 0x45, 0x5e,
	0xa1, 0x50, 0x80, 0x03, 0xaa, 0x93, 0x77, 0x0d, 0xb6, 0xc6, 0xcc, 0x6c, 0x7b, 0x6b, 0x30, 0xee,
	0xaa, 0x8e, 0xcf, 0x8c, 0x84, 0x4f, 0x60, 0x73, 0x79, 0xcc, 0x0e, 0xf5, 0xd4, 0x85, 0xaf, 0x0c,
	0xf8, 0x3f, 0x06, 0xfc, 0xa8, 0x18, 0x6e, 0x25, 0xef, 0x6f, 0xff, 0xdd, 0xc5, 0xc6, 0xb8, 0x39,
	0xf1, 0xa5, 0xb9, 0x89, 0x08, 0x6a, 0xf1, 0x71, 0x0c, 0x1f, 0xc1, 0xca, 0xfa, 0x03, 0x07, 0xf4,
	0xe5, 0x1f, 0xe8, 0xbd, 0x00, 0xf2, 0xa1, 0xd9, 0x8e, 0x62, 0x8f, 0x7b, 0xd4, 0xcc, 0x46, 0x29,
	0x7c, 0x86, 0x23, 0x2d, 0x76, 0x60, 0x5f, 0xfd, 0x62, 0x4f, 0x05, 0x91, 0x4f, 0x4d, 0x3f, 0xd5,
	0x3f, 0x9f, 0x74, 0xa9, 0xcd, 0x27, 0x39, 0x7c, 0x00, 0x93, 0x55, 0x1d, 0x9f, 0xb1, 0x32, 0x32,
	0x4b, 0xbe, 0x34, 0xfb, 0x58, 0xb1, 0x47, 0x2d, 0x6a, 0xb0, 0x7d, 0x48, 0x56, 0x72, 0xfb, 0xf6,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x17, 0x57, 0xbf, 0xd8, 0x7a, 0x02, 0x00, 0x00,
}
